### PR TITLE
Updated project to support dotnet 6

### PR DESCRIPTION
**Pull request by cheeto-bandito**
This should resolve the following issue: #7

### CODE REVIEW

**Comment by cheeto-bandito** [comment]
@patridge Are you the default reviewer for this repository?  I'm unable to add reviewers to the PR.  I think the Microsoft Learning community will appreciate this upgrade to dotnet6 to match the current version of Azure Cloud Shell.  Can you help with feedback or an approval?

**Comment by ktoliver** [comment]
@tamram @patridge @rmcmurray Fixes https://dev.azure.com/ceapex/Microsoft%20Learn/_workitems/edit/639554/; I tested the module using these values, and the module worked as expected.

**Comment by ktoliver** [comment]
@jboeshart @patridge - You've merged PRs in the repo. Author @tamram approved the updates. Would you be able to merge the fixes to support the live module? Thanks!

**Review by patridge — APPROVED** [review]

**Comment by cheeto-bandito** [comment]
@ktoliver Issue [#7](https://github.com/MicrosoftDocs/mslearn-control-access-to-azure-storage-with-sas/issues/7) can be closed now that this PR is merged.  Do you have permissions?

**Comment by ktoliver** [comment]
> @ktoliver Issue [#7](https://github.com/MicrosoftDocs/mslearn-control-access-to-azure-storage-with-sas/issues/7) can be closed now that this PR is merged. Do you have permissions?

@cheeto-bandito I do not have permissions.

**Pull request merged**
