### PR TITLE
Upgrade to dotnet 3.1 to support current Azure Cloudshell

### PR DESCRIPTION
**Pull request by unstableunicorn**
Updates to allow a fix for: #4 
* Update to global.json to 3.1.401 currently on Azure Cloudshell
* Added rollForward in global.json to latest minor for future compatibility
* Updated csproj to target netcoreapp3.1
* Updated csproj to remove unrequired package references and added updated package references for 3.1
* Updated startup to roll back initial changes and be compatible for 3.1

### CODE REVIEW

**Comment by patridge** [comment]
When I try this code in the [Learn exercise](https://docs.microsoft.com/en-us/learn/modules/control-access-to-azure-storage-with-sas/4-exercise-use-shared-access-signatures?source=learn), I get the following error message, with "Sign-in" as a link to authenticate with Azure.

> Unauthorized. Sign-in to authenticate and refresh this page.

Unfortunately, when I do authenticate, it doesn't fix the error message.

**Comment by unstableunicorn** [comment]
@patridge Hmm, I left the Authorize in there and didn't have an issue on my side, let me remove it, it should not be required for this exercise anyway. Do you mind testing again when I push the update?

**Comment by patridge** [comment]
Sadly, that didn't seem to help. It's almost like it's a problem with the authentication through the CLI proxy stuff, the things at the session-specific URL like this:: `https://gateway03.westus.console.azure.com/n/.../proxy/8000/`. I'm going to reach out to see if I can find someone with more experience in those systems.

**Comment by DylanMunyard** [comment]
@patridge I just completed the lesson https://docs.microsoft.com/en-us/learn/modules/control-access-to-azure-storage-with-sas/4-exercise-use-shared-access-signatures from the PR branch and it works a charm. I also had errors retrieving the image from the 'External companies' link before I realised I had not updated the `AccountName` setting to reflect my cloud session random name.

**Comment by patridge** [comment]
Thank you so much for the contribution, @unstableunicorn, and for the confirmation that it was working for you, @DylanMunyard.

**Pull request merged**
